import {
  FileImage,
  FileText,
  Combine,
  Split,
  Shrink,
  type LucideIcon,
  BookText,
  ImageUp,
  FileJson,
  FileUp,
  ScanText,
  X,
  RectangleHorizontal,
  FileScan,
  RefreshCcw,
  Plus,
  SquarePen,
  LockOpen,
  Lock,
  Signature,
  EyeOff,
  ShieldCheck,
} from 'lucide-react';

export type ToolCategory =
  | 'Organize PDF'
  | 'Optimize PDF'
  | 'Convert to PDF'
  | 'Convert from PDF'
  | 'Edit PDF'
  | 'PDF Security';

export type Tool = {
  slug: string;
  name: string;
  description: string;
  iconName: keyof typeof iconMap;
  icon: LucideIcon;
  color: string;
  accept?: string | string[];
  category: ToolCategory;
};

export const iconMap = {
  Combine,
  Split,
  Shrink,
  FileText,
  FileImage,
  BookText,
  ImageUp,
  FileJson,
  ScanText,
  FileUp,
  X,
  RectangleHorizontal,
  FileScan,
  RefreshCcw,
  Plus,
  SquarePen,
  LockOpen,
  Lock,
  Signature,
  EyeOff,
  ShieldCheck,
};

export const tools: Tool[] = [
  // Organize PDF
  {
    slug: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one single document.',
    iconName: 'Combine',
    icon: Combine,
    color: 'hsl(3, 80%, 62%)',
    accept: 'application/pdf',
    category: 'Organize PDF',
  },
  {
    slug: 'split-pdf',
    name: 'Split PDF',
    description: 'Extract one or more pages from your PDF.',
    iconName: 'Split',
    icon: Split,
    color: 'hsl(3, 80%, 62-%)',
    accept: 'application/pdf',
    category: 'Organize PDF',
  },
  {
    slug: 'remove-pages',
    name: 'Remove pages',
    description: 'Delete specific pages from a PDF file.',
    iconName: 'X',
    icon: X,
    color: 'hsl(3, 80%, 62%)',
    accept: 'application/pdf',
    category: 'Organize PDF',
  },
  {
    slug: 'extract-pages',
    name: 'Extract pages',
    description: 'Extract a set of pages from a PDF.',
    iconName: 'RectangleHorizontal',
    icon: RectangleHorizontal,
    color: 'hsl(3, 80%, 62%)',
    accept: 'application/pdf',
    category: 'Organize PDF',
  },
  {
    slug: 'organize-pdf',
    name: 'Organize PDF',
    description: 'Sort, add, and delete PDF pages.',
    iconName: 'Split',
    icon: Split,
    color: 'hsl(3, 80%, 62%)',
    accept: 'application/pdf',
    category: 'Organize PDF',
  },
  {
    slug: 'scan-to-pdf',
    name: 'Scan to PDF',
    description: 'Scan documents and convert to PDF.',
    iconName: 'FileScan',
    icon: FileScan,
    color: 'hsl(3, 80%, 62%)',
    accept: ['image/jpeg', 'image/png'],
    category: 'Organize PDF',
  },

  // Optimize PDF
  {
    slug: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce the size of your PDF without losing quality.',
    iconName: 'Shrink',
    icon: Shrink,
    color: 'hsl(92, 49%, 51%)',
    accept: 'application/pdf',
    category: 'Optimize PDF',
  },
  {
    slug: 'repair-pdf',
    name: 'Repair PDF',
    description: 'Fix corrupted or damaged PDF files.',
    iconName: 'RefreshCcw',
    icon: RefreshCcw,
    color: 'hsl(92, 49%, 51%)',
    accept: 'application/pdf',
    category: 'Optimize PDF',
  },
  {
    slug: 'ocr-pdf',
    name: 'OCR PDF',
    description: 'Make your scanned PDFs searchable and selectable.',
    iconName: 'FileScan',
    icon: FileScan,
    color: 'hsl(92, 49%, 51%)',
    accept: 'application/pdf',
    category: 'Optimize PDF',
  },
  
  // Convert to PDF
  {
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert JPG images to PDF documents.',
    iconName: 'FileImage',
    icon: FileImage,
    color: 'hsl(47, 98%, 52%)',
    accept: 'image/jpeg',
    category: 'Convert to PDF',
  },
  {
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents to PDF.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    accept: '.doc,.docx',
    category: 'Convert to PDF',
  },
  {
    slug: 'powerpoint-to-pdf',
    name: 'Powerpoint to PDF',
    description: 'Convert Powerpoint presentations to PDF.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    accept: '.ppt,.pptx',
    category: 'Convert to PDF',
  },
  {
    slug: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    accept: '.xls,.xlsx',
    category: 'Convert to PDF',
  },
  {
    slug: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert webpages in HTML to PDF.',
    iconName: 'FileJson',
    icon: FileJson,
    color: 'hsl(47, 98%, 52%)',
    accept: '.html',
    category: 'Convert to PDF',
  },

  // Convert from PDF
  {
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert PDF pages to JPG images.',
    iconName: 'FileImage',
    icon: FileImage,
    color: 'hsl(47, 98%, 52%)',
    accept: 'application/pdf',
    category: 'Convert from PDF',
  },
  {
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF to editable Word documents.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    accept: 'application/pdf',
    category: 'Convert from PDF',
  },
  {
    slug: 'pdf-to-powerpoint',
    name: 'PDF to Powerpoint',
    description: 'Convert PDF to editable Powerpoint presentations.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    accept: 'application/pdf',
    category: 'Convert from PDF',
  },
  {
    slug: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Convert PDF to editable Excel spreadsheets.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    accept: 'application/pdf',
    category: 'Convert from PDF',
  },
  {
    slug: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    description: 'Convert PDF to PDF/A for long-term archiving.',
    iconName: 'ShieldCheck',
    icon: ShieldCheck,
    color: 'hsl(47, 98%, 52%)',
    accept: 'application/pdf',
    category: 'Convert from PDF',
  },
  
  // Edit PDF
  {
    slug: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate your PDF pages as you need them.',
    iconName: 'RefreshCcw',
    icon: RefreshCcw,
    color: 'hsl(283, 75%, 53%)',
    accept: 'application/pdf',
    category: 'Edit PDF',
  },
  {
    slug: 'add-page-numbers',
    name: 'Add page numbers',
    description: 'Insert page numbers in your PDF.',
    iconName: 'Plus',
    icon: Plus,
    color: 'hsl(283, 75%, 53%)',
    accept: 'application/pdf',
    category: 'Edit PDF',
  },
  {
    slug: 'add-watermark',
    name: 'Add watermark',
    description: 'Stamp an image or text over your PDF.',
    iconName: 'ImageUp',
    icon: ImageUp,
    color: 'hsl(283, 75%, 53%)',
    accept: 'application/pdf',
    category: 'Edit PDF',
  },
  {
    slug: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Add text, shapes, comments and highlights.',
    iconName: 'SquarePen',
    icon: SquarePen,
    color: 'hsl(283, 75%, 53%)',
    accept: 'application/pdf',
    category: 'Edit PDF',
  },

  // PDF Security
  {
    slug: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password, encryption, and permissions from your PDF.',
    iconName: 'LockOpen',
    icon: LockOpen,
    color: 'hsl(215, 87%, 52%)',
    accept: 'application/pdf',
    category: 'PDF Security',
  },
  {
    slug: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Add a password and encrypt your PDF file.',
    iconName: 'Lock',
    icon: Lock,
    color: 'hsl(215, 87%, 52%)',
    accept: 'application/pdf',
    category: 'PDF Security',
  },
  {
    slug: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Sign your PDF files with an electronic signature.',
    iconName: 'Signature',
    icon: Signature,
    color: 'hsl(215, 87%, 52%)',
    accept: 'application/pdf',
    category: 'PDF Security',
  },
  {
    slug: 'redact-pdf',
    name: 'Redact PDF',
    description: 'Permanently remove sensitive content from your PDF.',
    iconName: 'EyeOff',
    icon: EyeOff,
    color: 'hsl(215, 87%, 52%)',
    accept: 'application/pdf',
    category: 'PDF Security',
  },
];
