import {
  FileImage,
  FileText,
  Combine,
  Split,
  Shrink,
  type LucideIcon,
  BookText,
  ImageUp,
  FileJson,
  FileUp,
  ScanText,
  RefreshCcw,
  RectangleHorizontal,
  X,
  FileScan,
  RotateCw,
  Plus,
  SquarePen,
  LockOpen,
  Lock,
  Signature,
  EyeOff,
  ShieldCheck,
  RotateCcw,
} from 'lucide-react';

export type Tool = {
  slug: string;
  name: string;
  description: string;
  iconName: keyof typeof iconMap;
  icon: LucideIcon;
  color: string;
  category: 'All' | 'Organize PDF' | 'Optimize PDF' | 'Convert to PDF' | 'Convert from PDF' | 'Edit PDF' | 'PDF Security';
  accept?: string | string[];
};

export const iconMap = {
  Combine,
  Split,
  Shrink,
  FileText,
  FileImage,
  BookText,
  ImageUp,
  FileJson,
  ScanText,
  FileUp,
  RefreshCcw,
  RectangleHorizontal,
  X,
  FileScan,
  RotateCcw,
  Plus,
  SquarePen,
  LockOpen,
  Lock,
  Signature,
  EyeOff,
  ShieldCheck,
};

export const tools: Tool[] = [
  {
    slug: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one single document.',
    iconName: 'Combine',
    icon: Combine,
    color: 'hsl(3, 80%, 62%)',
    accept: 'application/pdf',
    category: 'Organize PDF',
  },
  {
    slug: 'split-pdf',
    name: 'Split PDF',
    description: 'Extract one or more pages from your PDF.',
    iconName: 'Split',
    icon: Split,
    color: 'hsl(3, 80%, 62%)',
    accept: 'application/pdf',
    category: 'Organize PDF',
  },
  {
    slug: 'remove-pages',
    name: 'Remove pages',
    description: 'Remove one or multiple pages from your PDF.',
    iconName: 'X',
    icon: X,
    color: 'hsl(3, 80%, 62%)',
    accept: 'application/pdf',
    category: 'Organize PDF',
  },
  {
    slug: 'extract-pages',
    name: 'Extract pages',
    description: 'Extract pages from your PDF document.',
    iconName: 'RectangleHorizontal',
    icon: RectangleHorizontal,
    color: 'hsl(3, 80%, 62%)',
    accept: 'application/pdf',
    category: 'Organize PDF',
  },
  {
    slug: 'organize-pdf',
    name: 'Organize PDF',
    description: 'Sort, add, and delete PDF pages.',
    iconName: 'Split',
    icon: Split,
    color: 'hsl(3, 80%, 62%)',
    accept: 'application/pdf',
    category: 'Organize PDF',
  },
  {
    slug: 'scan-to-pdf',
    name: 'Scan to PDF',
    description: 'Scan documents directly to PDF format.',
    iconName: 'FileScan',
    icon: FileScan,
    color: 'hsl(3, 80%, 62%)',
    accept: ['image/jpeg', 'image/png'],
    category: 'Organize PDF',
  },
  {
    slug: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce the size of your PDF without losing quality.',
    iconName: 'Shrink',
    icon: Shrink,
    color: 'hsl(92, 49%, 51%)',
    accept: 'application/pdf',
    category: 'Optimize PDF',
  },
   {
    slug: 'compress-image',
    name: 'Compress Image',
    description: 'Reduce the size of your JPG or PNG without losing quality.',
    iconName: 'Shrink',
    icon: Shrink,
    color: 'hsl(92, 49%, 51%)',
    accept: 'image/jpeg,image/png',
    category: 'Optimize PDF',
  },
  {
    slug: 'ocr-pdf',
    name: 'OCR PDF',
    description: 'Make your PDF searchable and selectable.',
    iconName: 'FileScan',
    icon: FileScan,
    color: 'hsl(92, 49%, 51%)',
    accept: 'application/pdf',
    category: 'Optimize PDF',
  },
  {
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert JPG images to PDF documents.',
    iconName: 'FileImage',
    icon: FileImage,
    color: 'hsl(47, 98%, 52%)',
    accept: 'image/jpeg',
    category: 'Convert to PDF',
  },
  {
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents to PDF.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    accept: '.doc,.docx',
    category: 'Convert to PDF',
  },
  {
    slug: 'powerpoint-to-pdf',
    name: 'Powerpoint to PDF',
    description: 'Convert Powerpoint presentations to PDF.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    accept: '.ppt,.pptx',
    category: 'Convert to PDF',
  },
  {
    slug: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    accept: '.xls,.xlsx',
    category: 'Convert to PDF',
  },
  {
    slug: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert web pages to PDF.',
    iconName: 'FileJson',
    icon: FileJson,
    color: 'hsl(47, 98%, 52%)',
    category: 'Convert to PDF',
  },
  {
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert PDF pages to JPG images.',
    iconName: 'FileImage',
    icon: FileImage,
    color: 'hsl(47, 98%, 52%)',
    accept: 'application/pdf',
    category: 'Convert from PDF',
  },
  {
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF to editable Word documents.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    accept: 'application/pdf',
    category: 'Convert from PDF',
  },
  {
    slug: 'pdf-to-powerpoint',
    name: 'PDF to Powerpoint',
    description: 'Convert PDF to editable Powerpoint presentations.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    accept: 'application/pdf',
    category: 'Convert from PDF',
  },
  {
    slug: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Convert PDF to editable Excel spreadsheets.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    accept: 'application/pdf',
    category: 'Convert from PDF',
  },
  {
    slug: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    description: 'Convert PDF to PDF/A for long-term archiving.',
    iconName: 'ShieldCheck',
    icon: ShieldCheck,
    color: 'hsl(47, 98%, 52%)',
    accept: 'application/pdf',
    category: 'Convert from PDF',
  },
  {
    slug: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate all or specific pages in your PDF.',
    iconName: 'RotateCcw',
    icon: RotateCcw,
    color: 'hsl(283, 75%, 53%)',
    accept: 'application/pdf',
    category: 'Edit PDF',
  },
  {
    slug: 'add-page-numbers',
    name: 'Add page numbers',
    description: 'Insert page numbers into your PDF.',
    iconName: 'Plus',
    icon: Plus,
    color: 'hsl(283, 75%, 53%)',
    accept: 'application/pdf',
    category: 'Edit PDF',
  },
  {
    slug: 'add-watermark',
    name: 'Add watermark',
    description: 'Add a text or image watermark to your PDF.',
    iconName: 'ImageUp',
    icon: ImageUp,
    color: 'hsl(283, 75%, 53%)',
    accept: 'application/pdf',
    category: 'Edit PDF',
  },
  {
    slug: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove a password from your PDF.',
    iconName: 'LockOpen',
    icon: LockOpen,
    color: 'hsl(215, 87%, 52%)',
    accept: 'application/pdf',
    category: 'PDF Security',
  },
  {
    slug: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Add a password and encrypt your PDF.',
    iconName: 'Lock',
    icon: Lock,
    color: 'hsl(215, 87%, 52%)',
    accept: 'application/pdf',
    category: 'PDF Security',
  },
   {
    slug: 'summarize-pdf',
    name: 'Summarize PDF',
    description: 'Get a quick summary of any PDF document using AI.',
    iconName: 'BookText',
    icon: BookText,
    color: 'hsl(160, 84%, 39%)',
    accept: 'application/pdf',
    category: 'All',
  },
  {
    slug: 'host-image-to-url',
    name: 'Host Image to URL',
    description: 'Upload an image and get a shareable URL.',
    iconName: 'ImageUp',
    icon: ImageUp,
    color: 'hsl(283, 75%, 53%)',
    accept: 'image/*',
    category: 'All',
  },
   {
    slug: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert various image formats to PDF.',
    iconName: 'FileImage',
    icon: FileImage,
    color: 'hsl(47, 98%, 52%)',
    accept: 'image/jpeg,image/png,image/gif,image/bmp,image/tiff',
    category: 'Convert to PDF',
  },
  {
    slug: 'pdf-to-image',
    name: 'PDF to Image',
    description: 'Convert PDF pages to images (JPG, PNG).',
    iconName: 'FileImage',
    icon: FileImage,
    color: 'hsl(47, 98%, 52%)',
    accept: 'application/pdf',
    category: 'Convert from PDF',
  },
];
