import {
  FileImage,
  FileText,
  Combine,
  Split,
  Shrink,
  type LucideIcon,
  BookText,
  ImageUp,
  FileJson,
  X,
  FileScan,
  RefreshCcw,
  RotateCcw,
  ShieldCheck,
  Unlock,
  Plus,
  PenSquare,
  Lock,
  Signature,
  EyeOff,
  RectangleHorizontal,
} from 'lucide-react';

export type ToolCategory = 'Organize PDF' | 'Optimize PDF' | 'Convert to PDF' | 'Convert from PDF' | 'Edit PDF' | 'PDF Security';

export type Tool = {
  slug: string;
  name: string;
  description: string;
  iconName: keyof typeof iconMap;
  icon: LucideIcon;
  color: string;
  category: ToolCategory;
  accept?: string | string[];
};

export const iconMap = {
  Combine,
  Split,
  Shrink,
  FileText,
  FileImage,
  BookText,
  ImageUp,
  FileJson,
  X,
  FileScan,
  RefreshCcw,
  RotateCcw,
  ShieldCheck,
  Unlock,
  Plus,
  PenSquare,
  Lock,
  Signature,
  EyeOff,
  RectangleHorizontal,
};

export const tools: Tool[] = [
  // Organize PDF
  {
    slug: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one single document.',
    iconName: 'Combine',
    icon: Combine,
    color: 'hsl(3, 80%, 62%)',
    category: 'Organize PDF',
    accept: 'application/pdf',
  },
  {
    slug: 'split-pdf',
    name: 'Split PDF',
    description: 'Extract one or more pages from your PDF.',
    iconName: 'Split',
    icon: Split,
    color: 'hsl(3, 80%, 62%)',
    category: 'Organize PDF',
    accept: 'application/pdf',
  },
  {
    slug: 'remove-pages',
    name: 'Remove pages',
    description: 'Delete specific pages from a PDF file.',
    iconName: 'X',
    icon: X,
    color: 'hsl(3, 80%, 62%)',
    category: 'Organize PDF',
    accept: 'application/pdf',
  },
   {
    slug: 'extract-pages',
    name: 'Extract pages',
    description: 'Extract specific pages from a PDF file.',
    iconName: 'RectangleHorizontal',
    icon: RectangleHorizontal,
    color: 'hsl(3, 80%, 62%)',
    category: 'Organize PDF',
    accept: 'application/pdf',
  },
   {
    slug: 'organize-pdf',
    name: 'Organize PDF',
    description: 'Sort, add, and delete PDF pages.',
    iconName: 'Split',
    icon: Split,
    color: 'hsl(3, 80%, 62%)',
    category: 'Organize PDF',
    accept: 'application/pdf',
  },
  {
    slug: 'scan-to-pdf',
    name: 'Scan to PDF',
    description: 'Scan documents directly to PDF format.',
    iconName: 'FileScan',
    icon: FileScan,
    color: 'hsl(3, 80%, 62%)',
    category: 'Organize PDF',
    accept: ['image/jpeg', 'image/png'],
  },
  
  // Optimize PDF
  {
    slug: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce the size of your PDF without losing quality.',
    iconName: 'Shrink',
    icon: Shrink,
    color: 'hsl(92, 49%, 51%)',
    category: 'Optimize PDF',
    accept: 'application/pdf',
  },
  {
    slug: 'repair-pdf',
    name: 'Repair PDF',
    description: 'Attempt to fix a corrupted or damaged PDF file.',
    iconName: 'RefreshCcw',
    icon: RefreshCcw,
    color: 'hsl(92, 49%, 51%)',
    category: 'Optimize PDF',
    accept: 'application/pdf',
  },
  {
    slug: 'ocr-pdf',
    name: 'OCR PDF',
    description: 'Recognize text in a scanned PDF.',
    iconName: 'FileScan',
    icon: FileScan,
    color: 'hsl(92, 49%, 51%)',
    category: 'Optimize PDF',
    accept: 'application/pdf',
  },

  // Convert to PDF
  {
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert JPG images to a PDF document.',
    iconName: 'FileImage',
    icon: FileImage,
    color: 'hsl(47, 98%, 52%)',
    category: 'Convert to PDF',
    accept: 'image/jpeg',
  },
  {
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents to PDF.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    category: 'Convert to PDF',
    accept: '.doc,.docx',
  },
  {
    slug: 'powerpoint-to-pdf',
    name: 'Powerpoint to PDF',
    description: 'Convert Powerpoint presentations to PDF.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    category: 'Convert to PDF',
    accept: '.ppt,.pptx',
  },
  {
    slug: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    category: 'Convert to PDF',
    accept: '.xls,.xlsx',
  },
  {
    slug: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert web pages to PDF.',
    iconName: 'FileJson',
    icon: FileJson,
    color: 'hsl(47, 98%, 52%)',
    category: 'Convert to PDF',
  },

  // Convert from PDF
  {
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert each PDF page into a JPG image.',
    iconName: 'FileImage',
    icon: FileImage,
    color: 'hsl(47, 98%, 52%)',
    category: 'Convert from PDF',
    accept: 'application/pdf',
  },
  {
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert a PDF to an editable text file.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    category: 'Convert from PDF',
    accept: 'application/pdf',
  },
  {
    slug: 'pdf-to-powerpoint',
    name: 'PDF to Powerpoint',
    description: 'Convert PDF to Powerpoint presentations.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    category: 'Convert from PDF',
    accept: 'application/pdf',
  },
  {
    slug: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Convert PDF to Excel spreadsheets.',
    iconName: 'FileText',
    icon: FileText,
    color: 'hsl(47, 98%, 52%)',
    category: 'Convert from PDF',
    accept: 'application/pdf',
  },
  {
    slug: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    description: 'Convert PDF to an ISO-standardized version for archiving.',
    iconName: 'ShieldCheck',
    icon: ShieldCheck,
    color: 'hsl(47, 98%, 52%)',
    category: 'Convert from PDF',
    accept: 'application/pdf',
  },

  // Edit PDF
  {
    slug: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate your PDFs the way you need them.',
    iconName: 'RotateCcw',
    icon: RotateCcw,
    color: 'hsl(283, 75%, 53%)',
    category: 'Edit PDF',
    accept: 'application/pdf',
  },
  {
    slug: 'add-page-numbers',
    name: 'Add page numbers',
    description: 'Insert page numbers in your PDF.',
    iconName: 'Plus',
    icon: Plus,
    color: 'hsl(283, 75%, 53%)',
    category: 'Edit PDF',
    accept: 'application/pdf',
  },
  {
    slug: 'add-watermark',
    name: 'Add watermark',
    description: 'Stamp an image or text over your PDF.',
    iconName: 'ImageUp',
    icon: ImageUp,
    color: 'hsl(283, 75%, 53%)',
    category: 'Edit PDF',
    accept: 'application/pdf',
  },
  {
    slug: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Add text, shapes, comments and highlights to a PDF.',
    iconName: 'PenSquare',
    icon: PenSquare,
    color: 'hsl(283, 75%, 53%)',
    category: 'Edit PDF',
    accept: 'application/pdf',
  },

  // PDF Security
  {
    slug: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password security from your PDF.',
    iconName: 'Unlock',
    icon: Unlock,
    color: 'hsl(215, 87%, 52%)',
    category: 'PDF Security',
    accept: 'application/pdf',
  },
  {
    slug: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Add a password and encrypt your PDF file.',
    iconName: 'Lock',
    icon: Lock,
    color: 'hsl(215, 87%, 52%)',
    category: 'PDF Security',
    accept: 'application/pdf',
  },
  {
    slug: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Sign a document with your electronic signature.',
    iconName: 'Signature',
    icon: Signature,
    color: 'hsl(215, 87%, 52%)',
    category: 'PDF Security',
    accept: 'application/pdf',
  },
  {
    slug: 'redact-pdf',
    name: 'Redact PDF',
    description: 'Permanently remove sensitive information from your PDF.',
    iconName: 'EyeOff',
    icon: EyeOff,
    color: 'hsl(215, 87%, 52%)',
    category: 'PDF Security',
    accept: 'application/pdf',
  },
];
